### ISSUE TITLE
how to change title background color

### ISSUE THREAD

**Issue by AsadAlihp** [viethoa/custom-dialog#1]
Hi,
 I have been trying to change title background color which is 'ORANGE" by default. What should I do? is it changeable ?

**Comment by viethoa** [comment]
Can you try to add <color name="app_primary_color">#F44336</color>
into your colors.xml.

**Comment by AsadAlihp** [comment]
@viethoa Thanks for your reply. Its very easy to use very simple to implement. Its just what I want. I am using it but still unable to change title background color. and yes I added the color in colors.xml but how to set that color as dialogue ```title background``` color , Please guide me to change [this](http://imgur.com/a/Zgvb9) color .http://imgur.com/a/Zgvb9

**Comment by AsadAlihp** [comment]
![screenshot from 2017-05-15 15 50 15](https://cloud.githubusercontent.com/assets/7264209/26055286/b424ba48-3989-11e7-8914-24b4a0e69e37.png)

**Comment by viethoa** [comment]
Sorry for my mistake, I using *dialog_title_bg.xml* in drawable to set background for the title. You can custom that file in your project, I mean you just need to create a .xml file with name dialog_title_bg.xml and then make it to whatever do you want. I also put my currently code below, you can just copy it and change the color

[dialog_title_bg.txt](https://github.com/viethoa/custom-dialog-android/files/1003399/dialog_title_bg.txt)

**Comment by viethoa** [comment]
That is the oldest library I have created for my first project in android. So now I don't do any update for it. Because now we have material design and maybe I will update into new version for that.
